# Generated by Django 4.2.7 on 2023-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='img',
            field=models.ImageField(default='aaa', upload_to='pics'),
            preserve_default=False,
        ),
    ]
